title = "Notre-Dame de Paris"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true

[languages]
[languages.en]
title = "CAPP 4 Good"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
# [languages.es]
# title = "CAPP 4 Good"
# weight = 2
# contentDir = "content/es"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = "#000000"
author = " "
favicon = ""
site_logo = ""
description = " "
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-gray"
recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[caches]
  [caches.images]
    dir = ':cacheDir/images'